[package]
name = "debugger"
version = "0.1.0"
edition = "2021"
default-run = "debugger"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
emu = { path = "../emu"}
eframe = "0.26.2"
native-dialog = "0.7.0"
rodio = "0.19.0"